services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - sukuna_network

  redis:
    image: redis:6.2
    container_name: redis-container
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - sukuna_network

  eureka-server:
    image: a1a4a7/my-eureka-server
    container_name: eureka-server
    restart: unless-stopped
    ports:
      - "8761:8761"
    networks:
      - sukuna_network
    environment:
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: 'false'
      EUREKA_CLIENT_FETCH_REGISTRY: 'false'
      EUREKA_SERVER_WAIT_TIME_IN_MS_WHEN_SYNC_EMPTY: 0

  db-cache-service:
    build: ./db-cache-service
    container_name: db-cache-service
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - sukuna_network
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_PROFILES_ACTIVE: docker

  auth-service:
    build: ./auth-service
    container_name: auth-service
    restart: unless-stopped
    ports:
      - "9004:9004"
    depends_on:
      - db-cache-service
      - eureka-server
      - mysql
      - redis
    networks:
      - sukuna_network
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_PROFILES_ACTIVE: docker

  api-gateway-service:
    build: ./api-gateway-service
    container_name: api-gateway-service
    restart: unless-stopped
    ports:
      - "9000:9000"
    depends_on:
      - eureka-server
      - auth-service
      - db-cache-service
    networks:
      - sukuna_network
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_PROFILES_ACTIVE: docker

  zookeeper:
    image: zookeeper:3.6
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - sukuna_network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - sukuna_network

  message-queue-service:
    build: ./message-queue-service
    container_name: message-queue-service
    restart: unless-stopped
    networks:
      - sukuna_network
    depends_on:
      - kafka
      - mysql

  order-service:
    build: ./order-service
    container_name: order-service
    restart: unless-stopped
    ports:
      - "9001:9001"
    networks:
      - sukuna_network
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - kafka
      - mysql

volumes:
  mysql-data:
  redis-data:
  redis-insight:

networks:
  sukuna_network:
    name: sukuna_network
    driver: bridge
