version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - sukuna_network

  redis:
    image: redis:6.2
    container_name: redis-container
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - sukuna_network

  db-cache-service:
    build:
      context: ./db-cache-service
    container_name: db-cache-service
    ports:
      - "8081:8081"
    networks:
      - sukuna_network

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8080:8080"
    depends_on:
      db-cache-service:
        condition: service_started
    networks:
      - sukuna_network

volumes:
  mysql-data:
  redis-data:

networks:
  sukuna_network:
    name: sukuna_network
    driver: bridge
